[package]
name = "file_hasher"
version = "0.1.0"
authors = ["Andreas Ejdesgaard <andreasejdesgaard@protonmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
blake2 = "0.7.1"
chrono = "0.4.0"
