array_width = 100
attr_fn_like_width = 100
binop_separator = "Back"
blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
chain_width = 100
combine_control_expr = true
condense_wildcard_suffixes = false
control_brace_style = "ClosingNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Compressed"
fn_call_width = 100
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_bodies = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 140
merge_derives = true
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 100
space_after_colon = true
spaces_around_ranges = false
space_before_colon = false
struct_field_align_threshold = 40
struct_lit_single_line = true
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = false