[package]
name = "file_hasher_core"
version = "1.0.6"
authors = ["Andreas Ejdesgaard <andreasejdesgaard@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
blake2 = "0.9.0"
chrono = "0.4.13"
hex = "0.4.2"
rayon = "1.3.1"
join = "0.1.1"
