[package]
name = "file_hasher_core"
version = "1.0.6"
authors = ["Andreas Ejdesgaard <andreasejdesgaard@protonmail.com>"]
edition = "2018"

[dependencies]
blake2 = "0.8.1"
chrono = "0.4.11"
hex = "0.4.2"
rayon = "1.3.0"
join = "0.1.1"
