[package]
name = "file_hasher_core"
version = "1.0.8"
authors = ["Andreas Ejdesgaard <andreasejdesgaard@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
blake2 = "0.9.1"
chrono = "0.4.19"
hex = "0.4.2"
rayon = "1.5.0"
join = "0.1.1"
